### ISSUE TITLE
Product Roadmap

### ISSUE THREAD

**Issue by jackdixonryan** [jackdixonryan/trepik#6]
## Description
I'll leave this one nice and simple. Complete the items below. Once completed, add the product roadmap ( or a link to it ) to the description of the Milestone. Only then may you mark this as complete.

## WTBD
- [ ] Figure out what a product roadmap is
- [ ] Figure out how to construct one 
- [ ] Create a Product Roadmap for MLP
